name: Build

on:
  workflow_call:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version-file: ".node-version"

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: npm ci
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
          retention-days: 1
